# use ubuntu 17.04
FROM hub.c.163.com/library/ubuntu:yakkety

RUN apt-get update
RUN apt-get install vim -y

# install gcc
RUN apt-get install build-essential -y; exit 0
RUN apt-get install gcc-5 -y



